sudo: required
language: generic

services:
  - docker

before_install:
  - docker 
  - docker build -t indranil1981/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true indranil1981/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker'
  env: 'Dockerreact-env'
  bucket_name: 'elasticbeanstalk-us-east-1-467943707514'
  bucket_path: 'docker'
  on:
    branch: main
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"

